# Generated by Django 5.0 on 2024-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='current_watch_time',
            field=models.IntegerField(default=0),
        ),
    ]
