# Generated by Django 5.0 on 2024-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_userlesson_current_watch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='payment_type',
            field=models.CharField(choices=[(None, ''), ('PM', 'Payme'), ('AP', 'Apelsin'), ('CL', 'Click'), ('VS', 'Visa')], default='', max_length=2),
        ),
    ]
