# Generated by Django 5.0 on 2024-01-31 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_unique_together_userlesson1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category/%Y/%m/%d'),
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('user', 'lesson')},
        ),
        migrations.DeleteModel(
            name='UserLesson1',
        ),
    ]
