# Generated by Django 5.0 on 2024-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_usercourse_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='payment_type',
            field=models.CharField(choices=[(None, None), ('PM', 'Payme'), ('AP', 'Apelsin'), ('CL', 'Click'), ('VS', 'Visa')], default=None, max_length=2),
        ),
    ]
